"""empty message

Revision ID: 2481b1a7db6a
Revises: c055a67fd1a3
Create Date: 2017-09-24 15:43:14.739367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2481b1a7db6a'
down_revision = 'c055a67fd1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_shorthand', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'github_shorthand')
    # ### end Alembic commands ###
