"""empty message

Revision ID: c055a67fd1a3
Revises: 
Create Date: 2017-09-18 22:39:04.326659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c055a67fd1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stub', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('api_key', name=op.f('uq_project_api_key')),
    sa.UniqueConstraint('name', name=op.f('uq_project_name')),
    sa.UniqueConstraint('stub', name=op.f('uq_project_stub'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_changed_password', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('commit', sa.String(length=64), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_build_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_build')),
    sa.UniqueConstraint('number', 'project_id', name='uq_build_number_project_id')
    )
    op.create_table('user_project_subscription',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_user_project_subscription_project_id_project')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_project_subscription_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_project_subscription')
    op.drop_table('build')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
